"""Init-detection MVP bench (astichi-composed, 10-field shape).

Per `OptimalReferencePlan.md §Phase 3` (simplified MVP shape): one hot
`get_all` measurement per candidate mechanism. The hot init-detection
check dominates real workloads in `pyrolyze.lifecycle`-shaped code
(millions of accesses per instance lifetime), so the candidate that
wins this measurement by a comfortable margin is the recommended pick.

Each candidate store carries `N_FIELDS` per-field slots. The bench
times a single `get_all(self)` method per call that runs the
init-detection check for every field, accumulates every field value
into a local `x` (`x += self.fX`), and returns `x` so CPython cannot
dead-code the loop body. The accumulator is applied uniformly to
every candidate so the per-field hot-path cost it adds (one extra
`LOAD_ATTR + BINARY_OP + STORE_FAST` triple, ~6 ns/field on
3.13/3.14) is the same constant on each row and does not bias the
ranking. The cold-path branches still execute on first call, which
is what proves correctness: the bench warms up by calling
`get_all()` once before timing, after which every field is initialised
and every per-field branch becomes a pure init-detection check
followed by the accumulator read.

Candidate code is generated by **astichi composition**: each
candidate's class body is a parent shell with `astichi_hole(...)`
slots, and each slot is filled by a single contribution that uses
an `astichi_for(...)` loop over a per-field spec tuple. Tuple-target
decomposition (`for (bit, payload, field) in astichi_for(...)`) binds
each spec element to its own loop variable; astichi unroll then
substitutes loop-variable references with the literal value at every
use site. Numeric specs (`1<<i`, `42+i`) flow into ordinary
expression positions and emit as integer constants; the per-field
attribute path flows into `astichi_ref(field).astichi_v` (or the
read form `astichi_ref(field)`) and lowers to the corresponding
`self.fX` attribute chain at materialize time.

Bitmask shares a local `m = self._mask` across the per-field
contribution via `astichi_import(m)` (placed outside the unrolled
loop) + `arg_names={"m": "m"}` so each cold-path branch updates the
cached mask. Gen-counter shares a local `g = self._store_gen` via
free-Load resolution (the contribution only reads `g`, never stores
to it, so the Load is naturally threaded onto the parent's binding
without `astichi_import`).

The fully-composed source for each store is exposed as
`<class>._GEN_SRC` for inspection / regression diff.

Decision rules:

- gap >= 15% across the top two candidates -> clear winner; record and
  proceed to optimal-reference work.
- gap < 15% -> run the bulk-clear tie-breaker (separate file, added on
  demand).
- per-Python-version anomaly -> investigate before scaling.

Run on multiple Python versions via `uv run --python <ver>` against
`yidl/docs/validation/perf/version_matrix.py`. The bench itself does
not enumerate the matrix; it prints one row per candidate for the
interpreter it is invoked under.

This file is a deliberately scoped MVP. The elaborate facade-over-store
shape recorded in `OptimalReferencePlan.md §Phase 3 (locked plan)` is
a contingent fallback, not a prerequisite.
"""

from __future__ import annotations

import gc
import sys
import time
from collections.abc import Callable
from dataclasses import dataclass

import astichi
from astichi.model import BasicComposable


N_FIELDS: int = 10

_VOID = object()


# ---------------------------------------------------------------------------
# Candidate construction via astichi composition.
#
# Each builder function returns the realised Python class. Pattern:
#
#   1. Build a parent class shell with `astichi_hole(<slot>)` markers
#      (and any candidate-specific preamble: `m = self._mask` for
#      bitmask, `g = self._store_gen` for gen-counter).
#
#   2. Build one contribution per hole. Each contribution wraps its
#      per-field block in an `astichi_for([(spec_0, ...), (spec_1, ...),
#      ...])` loop with a tuple-decomposition target so each spec
#      element binds to its own name. Per-field attribute paths use
#      `astichi_ref(field)` / `astichi_ref(field).astichi_v` and lower
#      to `self.fX` / `self.fX = ...` at materialize time.
#
#   3. Wire each contribution into the corresponding hole.
#
#   4. Build with `unroll=True`, materialise, emit Python source, exec
#      into a namespace, and return the class object. The emitted
#      source is also stashed as `<class>._GEN_SRC` for inspection.
# ---------------------------------------------------------------------------


def _build_class_from(
    *,
    parent_src: str,
    contributions: list[tuple[str, BasicComposable, dict[str, object]]],
    extra_globals: dict[str, object] | None = None,
) -> type:
    """Wire per-hole contributions into `parent_src`, build, exec, return class.

    `contributions` is `[(target_hole, composable, add_kwargs), ...]`.
    Build runs with `unroll=True` so `astichi_for` loops inside any
    contribution expand before splice.
    """
    builder = astichi.build()
    builder.add.Root(astichi.compile(parent_src))
    for idx, (target_hole, composable, add_kwargs) in enumerate(contributions):
        name = f"C{idx}"
        builder.add.__getattr__(name)(composable)
        target_handle = getattr(getattr(builder.Root, target_hole), "add")
        getattr(target_handle, name)(order=idx, **add_kwargs)
    source = builder.build(unroll=True).materialize().emit(provenance=False)
    namespace: dict[str, object] = {"_VOID": _VOID}
    if extra_globals:
        namespace.update(extra_globals)
    exec(compile(source, "<init_detection_mvp>", "exec"), namespace)
    cls_name = parent_src.split("class ", 1)[1].split(":", 1)[0].split("(", 1)[0].strip()
    cls = namespace[cls_name]
    assert isinstance(cls, type)
    cls._GEN_SRC = source  # type: ignore[attr-defined]
    return cls


def _slot_tuple(extra: tuple[str, ...] = ()) -> str:
    """Render a `__slots__` tuple literal for N_FIELDS data slots plus extras."""
    slots = tuple(f"f{i}" for i in range(N_FIELDS)) + extra
    return repr(slots)


def _build_bitmask_store() -> type:
    parent_src = (
        f"class BitmaskStore:\n"
        f"    __slots__ = {_slot_tuple(('_mask',))}\n"
        f"    def __init__(self):\n"
        f"        self._mask = 0\n"
        f"    def get_all(self):\n"
        f"        m = self._mask\n"
        f"        x = 0\n"
        f"        astichi_keep(x)\n"
        f"        astichi_hole(get_body)\n"
        f"        self._mask = m\n"
        f"        return x\n"
    )
    specs = tuple((1 << i, 42 + i, f"self.f{i}") for i in range(N_FIELDS))
    contribution = astichi.compile(
        f"astichi_import(m)\n"
        f"astichi_keep(x)\n"
        f"for (bit, payload, field) in astichi_for({specs!r}):\n"
        f"    if not (m & bit):\n"
        f"        astichi_ref(field).astichi_v = payload\n"
        f"        m |= bit\n"
        f"    x += astichi_ref(field)\n"
    )
    return _build_class_from(
        parent_src=parent_src,
        contributions=[("get_body", contribution, {"arg_names": {"m": "m"}})],
    )


def _build_void_store() -> type:
    parent_src = (
        f"class VoidStore:\n"
        f"    __slots__ = {_slot_tuple()}\n"
        f"    def __init__(self):\n"
        f"        astichi_hole(init_body)\n"
        f"    def get_all(self):\n"
        f"        x = 0\n"
        f"        astichi_keep(x)\n"
        f"        astichi_hole(get_body)\n"
        f"        return x\n"
    )
    fields = tuple(f"self.f{i}" for i in range(N_FIELDS))
    init_contrib = astichi.compile(
        f"for field in astichi_for({fields!r}):\n"
        f"    astichi_ref(field).astichi_v = _VOID\n"
    )
    get_specs = tuple((f"self.f{i}", 42 + i) for i in range(N_FIELDS))
    get_contrib = astichi.compile(
        f"astichi_keep(x)\n"
        f"for (field, payload) in astichi_for({get_specs!r}):\n"
        f"    if astichi_ref(field) is _VOID:\n"
        f"        astichi_ref(field).astichi_v = payload\n"
        f"    x += astichi_ref(field)\n"
    )
    return _build_class_from(
        parent_src=parent_src,
        contributions=[
            ("init_body", init_contrib, {}),
            ("get_body", get_contrib, {}),
        ],
    )


def _build_tryexcept_store() -> type:
    parent_src = (
        f"class TryExceptStore:\n"
        f"    __slots__ = {_slot_tuple()}\n"
        f"    def get_all(self):\n"
        f"        x = 0\n"
        f"        astichi_keep(x)\n"
        f"        astichi_hole(get_body)\n"
        f"        return x\n"
    )
    specs = tuple((f"self.f{i}", 42 + i) for i in range(N_FIELDS))
    contribution = astichi.compile(
        f"astichi_keep(x)\n"
        f"for (field, payload) in astichi_for({specs!r}):\n"
        f"    try:\n"
        f"        x += astichi_ref(field)\n"
        f"    except AttributeError:\n"
        f"        astichi_ref(field).astichi_v = payload\n"
        f"        x += astichi_ref(field)\n"
    )
    return _build_class_from(
        parent_src=parent_src,
        contributions=[("get_body", contribution, {})],
    )


def _build_gen_counter_store() -> type:
    gen_slots = tuple(f"_f{i}_gen" for i in range(N_FIELDS))
    parent_src = (
        f"class GenCounterStore:\n"
        f"    __slots__ = {_slot_tuple(gen_slots + ('_store_gen',))}\n"
        f"    def __init__(self):\n"
        f"        self._store_gen = 1\n"
        f"        astichi_hole(init_body)\n"
        f"    def get_all(self):\n"
        f"        g = self._store_gen\n"
        f"        x = 0\n"
        f"        astichi_keep(x)\n"
        f"        astichi_hole(get_body)\n"
        f"        return x\n"
    )
    init_fields = tuple(f"self._f{i}_gen" for i in range(N_FIELDS))
    init_contrib = astichi.compile(
        f"for field_gen in astichi_for({init_fields!r}):\n"
        f"    astichi_ref(field_gen).astichi_v = 0\n"
    )
    # `g` is a free Load inside the per-field block; after splice it
    # resolves to the parent's local `g = self._store_gen` (no
    # `astichi_import` needed because the contribution never stores g).
    get_specs = tuple(
        (f"self.f{i}", f"self._f{i}_gen", 42 + i) for i in range(N_FIELDS)
    )
    get_contrib = astichi.compile(
        f"astichi_keep(x)\n"
        f"for (field, field_gen, payload) in astichi_for({get_specs!r}):\n"
        f"    if astichi_ref(field_gen) != g:\n"
        f"        astichi_ref(field).astichi_v = payload\n"
        f"        astichi_ref(field_gen).astichi_v = g\n"
        f"    x += astichi_ref(field)\n"
    )
    return _build_class_from(
        parent_src=parent_src,
        contributions=[
            ("init_body", init_contrib, {}),
            ("get_body", get_contrib, {}),
        ],
    )


BitmaskStore = _build_bitmask_store()
VoidStore = _build_void_store()
TryExceptStore = _build_tryexcept_store()
GenCounterStore = _build_gen_counter_store()


# ---------------------------------------------------------------------------
# Bench harness: one batch = N tight `get_all()` calls in a loop, with
# the returned scalar XOR-folded into an accumulator the loop can't elide.
#
# Statistical hygiene per `OptimalReferencePlan.md §Phase 3 Metrics`:
# - `time.perf_counter_ns()` at batch boundaries
# - `gc.disable()` inside the timed region
# - 3 warm-up batches discarded
# - B = 21 measurement batches
# - median ns/field as the primary statistic; min/p95 for sanity
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class BenchResult:
    name: str
    median_ns_per_field: float
    median_ns_per_call: float
    min_ns_per_field: float
    p95_ns_per_field: float
    spread_pct: float  # (max - min) / median * 100

    def fmt(self) -> str:
        return (
            f"{self.name:11s}  median={self.median_ns_per_field:6.2f} ns/field  "
            f"({self.median_ns_per_call:6.1f} ns/get_all)  "
            f"min={self.min_ns_per_field:6.2f}  "
            f"p95={self.p95_ns_per_field:6.2f}  "
            f"spread={self.spread_pct:5.1f}%"
        )


def _run_one_batch(get_all: Callable[[], int], n: int) -> int:
    """One timed batch. Returns elapsed nanoseconds for the whole batch."""
    gc_was_enabled = gc.isenabled()
    gc.disable()
    acc = 0
    try:
        t0 = time.perf_counter_ns()
        for _ in range(n):
            acc ^= get_all()
        t1 = time.perf_counter_ns()
    finally:
        gc.collect()
        if gc_was_enabled:
            gc.enable()
    # Force the accumulator to be observed so CPython cannot dead-code
    # the loop body. `get_all()` returns `sum(42..42+N_FIELDS-1)` for
    # every candidate (== 465 with N_FIELDS=10), so `acc` cycles
    # between 0 and 465 across iterations; the comparison below is
    # structurally unreachable but the read still creates the data
    # dependency.
    if acc == -1:  # pragma: no cover -- impossible for our payloads
        print(acc)
    return t1 - t0


def bench(name: str, factory: Callable[[], object], *, n: int = 1_000_000,
          warmup: int = 3, batches: int = 21) -> BenchResult:
    store = factory()
    get_all = store.get_all  # bound method; pulled out of the loop
    # Force first init so subsequent `get_all` calls hit the hot path
    # for every field uniformly.
    get_all()
    for _ in range(warmup):
        _run_one_batch(get_all, n)
    samples = sorted(_run_one_batch(get_all, n) for _ in range(batches))
    median_total = samples[len(samples) // 2]
    p95_idx = max(0, int(round(0.95 * (len(samples) - 1))))
    median_ns_per_call = median_total / n
    return BenchResult(
        name=name,
        median_ns_per_field=median_ns_per_call / N_FIELDS,
        median_ns_per_call=median_ns_per_call,
        min_ns_per_field=(samples[0] / n) / N_FIELDS,
        p95_ns_per_field=(samples[p95_idx] / n) / N_FIELDS,
        spread_pct=(samples[-1] - samples[0]) / median_total * 100.0,
    )


# ---------------------------------------------------------------------------
# Cold-path bench: cost of constructing a fresh instance + the FIRST
# `get_all()` call on it. The first call is what exercises every
# candidate's cold-path branch on every field (tryexcept raises and
# catches AttributeError 10 times; the other three take their
# init-taken branch 10 times and write the slot).
#
# Methodology per batch:
#   1. Allocate `n` fresh instances and time the construction loop.
#   2. Call `inst.get_all()` once on each freshly-constructed instance
#      and time that loop.
#   3. Per-instance ns = (construct_ns + first_call_ns) / n.
#      Per-field ns    = first_call_ns / (n * N_FIELDS).
#
# `n` is much smaller than the warm bench (10_000 vs 1_000_000) because
# every iteration allocates a real Python object — the bench cost is
# dominated by allocation, not loop overhead. `gc.disable()` runs over
# the construction + first-call windows to keep collection cycles out
# of the timed regions; we explicitly `gc.collect()` between batches
# so the surviving instance lists from earlier batches are reclaimed.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ColdResult:
    name: str
    construct_ns: float          # median ns per construct()
    first_call_ns: float         # median ns per first get_all()
    first_call_per_field_ns: float
    total_per_instance_ns: float  # construct + first_call
    # Number of warm `get_all()` calls per instance until tryexcept's
    # cold-path investment pays off vs THIS candidate. None when this
    # row IS tryexcept; +inf when tryexcept's warm-path is no faster
    # than this candidate's (so it never pays off).
    tryexcept_breakeven_calls: float | None

    def fmt(self) -> str:
        be = (
            f"tryexcept_pays_off@{self.tryexcept_breakeven_calls:6.1f} calls"
            if self.tryexcept_breakeven_calls is not None
            else "(reference)"
        )
        return (
            f"{self.name:11s}  "
            f"construct={self.construct_ns:7.0f} ns  "
            f"first_call={self.first_call_ns:8.0f} ns  "
            f"({self.first_call_per_field_ns:6.1f} ns/field)  "
            f"total={self.total_per_instance_ns:8.0f} ns/instance  {be}"
        )


def _cold_one_batch(
    factory: Callable[[], object], n: int
) -> tuple[int, int]:
    """Time `n` constructs + `n` first-call get_all()s. Returns
    `(construct_ns, first_call_ns)`."""
    gc_was_enabled = gc.isenabled()
    gc.disable()
    try:
        t0 = time.perf_counter_ns()
        instances = [factory() for _ in range(n)]
        t1 = time.perf_counter_ns()
        # Distinct loop so the construction time and the first-call
        # time are isolated. Each `inst.get_all()` is the FIRST call
        # on that instance, so it traverses every cold-path branch.
        acc = 0
        t2 = time.perf_counter_ns()
        for inst in instances:
            acc ^= inst.get_all()
        t3 = time.perf_counter_ns()
    finally:
        # Drop the instances and reclaim before re-enabling gc so
        # the next batch starts from a clean slate.
        instances = None  # noqa: F841 -- explicit drop for the gc
        gc.collect()
        if gc_was_enabled:
            gc.enable()
    if acc == -1:  # pragma: no cover -- structurally impossible
        print(acc)
    return (t1 - t0), (t3 - t2)


def cold_bench(
    name: str,
    factory: Callable[[], object],
    *,
    n: int = 10_000,
    warmup: int = 2,
    batches: int = 11,
    warm_ns_per_field: float | None = None,
    tryexcept_total_per_instance_ns: float | None = None,
    tryexcept_warm_ns_per_field: float | None = None,
) -> ColdResult:
    """Cold-path bench. See module-level comment for methodology.

    `warm_ns_per_field` is this candidate's warm hot-path cost (from the
    main bench) and is used only to compute the break-even point against
    `tryexcept`'s total per-instance cost.
    """
    for _ in range(warmup):
        _cold_one_batch(factory, n)
    samples = [_cold_one_batch(factory, n) for _ in range(batches)]
    construct_samples = sorted(s[0] for s in samples)
    first_samples = sorted(s[1] for s in samples)
    construct_median = construct_samples[len(construct_samples) // 2] / n
    first_median = first_samples[len(first_samples) // 2] / n
    total = construct_median + first_median

    # Break-even: number of warm calls per instance until tryexcept's
    # per-instance setup overhead is amortized vs THIS candidate.
    # After K warm calls, total cost per instance is:
    #     this:      this_total      + K * N_FIELDS * this_warm
    #     tryexcept: tryexcept_total + K * N_FIELDS * tryexcept_warm
    # tryexcept overtakes when:
    #     K = (tryexcept_total - this_total)
    #         / (N_FIELDS * (this_warm - tryexcept_warm))
    breakeven: float | None
    if name == "tryexcept" or tryexcept_total_per_instance_ns is None:
        breakeven = None
    elif (
        warm_ns_per_field is None
        or tryexcept_warm_ns_per_field is None
        or warm_ns_per_field <= tryexcept_warm_ns_per_field
    ):
        # tryexcept's warm path is not faster than this candidate's,
        # so the setup overhead is never amortized.
        breakeven = float("inf")
    else:
        setup_deficit = tryexcept_total_per_instance_ns - total
        per_call_savings = N_FIELDS * (
            warm_ns_per_field - tryexcept_warm_ns_per_field
        )
        breakeven = (
            setup_deficit / per_call_savings if per_call_savings > 0 else float("inf")
        )

    return ColdResult(
        name=name,
        construct_ns=construct_median,
        first_call_ns=first_median,
        first_call_per_field_ns=first_median / N_FIELDS,
        total_per_instance_ns=total,
        tryexcept_breakeven_calls=breakeven,
    )


# ---------------------------------------------------------------------------
# Entry point.
# ---------------------------------------------------------------------------


CANDIDATES: tuple[tuple[str, Callable[[], object]], ...] = (
    ("bitmask", BitmaskStore),
    ("void", VoidStore),
    ("tryexcept", TryExceptStore),
    ("gen-counter", GenCounterStore),
)


def main() -> None:
    print("# init-detection MVP bench (astichi-composed, 10-field shape)")
    print(f"# python={sys.version.split()[0]}  implementation={sys.implementation.name}")
    print(f"# astichi={astichi.__version__}")
    print(f"# field count = {N_FIELDS}  primitive=time.perf_counter_ns()")
    print()
    print("## Warm bench (N=1_000_000  warmup=3  batches=21)")
    print("## per-field hot path = init-detection check + `x += self.fX` accumulator")
    print()
    warm_results: list[BenchResult] = []
    for name, factory in CANDIDATES:
        result = bench(name, factory)
        warm_results.append(result)
        print(result.fmt())

    print()
    ranked = sorted(warm_results, key=lambda r: r.median_ns_per_field)
    winner = ranked[0]
    runner_up = ranked[1]
    gap_pct = (
        (runner_up.median_ns_per_field - winner.median_ns_per_field)
        / winner.median_ns_per_field
        * 100.0
    )
    print(f"# warm winner: {winner.name} ({winner.median_ns_per_field:.2f} ns/field)")
    print(f"# warm runner-up: {runner_up.name} ({runner_up.median_ns_per_field:.2f} ns/field)")
    print(f"# warm gap winner vs runner-up: {gap_pct:.1f}%")

    print()
    print("## Cold bench (n_instances=10_000  warmup=2  batches=11)")
    print("## per-instance = construct + first get_all() (every cold branch fires)")
    print()
    warm_by_name = {r.name: r.median_ns_per_field for r in warm_results}
    # First pass: bench tryexcept so we know its per-instance + warm
    # cost for the break-even computation on the others.
    tryexcept_total = None
    tryexcept_warm = warm_by_name["tryexcept"]
    cold_results: list[ColdResult] = []
    for name, factory in CANDIDATES:
        if name == "tryexcept":
            r = cold_bench(name, factory, warm_ns_per_field=warm_by_name[name])
            tryexcept_total = r.total_per_instance_ns
            cold_results.append(r)
            break
    for name, factory in CANDIDATES:
        if name == "tryexcept":
            continue
        r = cold_bench(
            name,
            factory,
            warm_ns_per_field=warm_by_name[name],
            tryexcept_total_per_instance_ns=tryexcept_total,
            tryexcept_warm_ns_per_field=tryexcept_warm,
        )
        cold_results.append(r)
    # Re-order to match CANDIDATES.
    cold_by_name = {r.name: r for r in cold_results}
    for name, _factory in CANDIDATES:
        print(cold_by_name[name].fmt())

    print()
    print("# tryexcept_pays_off@K  reads: K warm `get_all()` calls per")
    print("# instance is the point at which tryexcept's larger setup cost")
    print("# (cold-path AttributeError x N_FIELDS) is paid back by its")
    print("# faster warm-path. K=0 means tryexcept is already cheaper")
    print("# even on first use; K=inf means the alternative's warm-path")
    print("# is no slower than tryexcept's so the cold investment never")
    print("# amortizes.")
    if gap_pct >= 15.0:
        print("# warm-bench decision: clear winner (>=15% gap); record and proceed.")
    else:
        print("# warm-bench decision: ambiguous (<15% gap); run bulk-clear tie-breaker.")


if __name__ == "__main__":
    main()
