"""Tests for yidl.cli."""

import sys
from pathlib import Path

import pytest

from yidl.cli import generate_api, main, map_type_hint
from yidl.parser import AST, InputNode, TransducerNode

_REPO_ROOT = Path(__file__).resolve().parents[1]
_EXAMPLE_SPEC = _REPO_ROOT / "example" / "example.yidl"


def test_map_type_hint_primitives_and_optional():
    assert map_type_hint("@id") == "str"
    assert map_type_hint("@str") == "str"
    assert map_type_hint("@bool") == "bool"
    assert map_type_hint("@type") == "Any"
    assert map_type_hint("?@object(Any)") == "Optional[Any]"
    assert map_type_hint("@lambda[@self]") == "Callable"


def test_generate_api_single_transducer():
    ast = AST(
        transducers=[
            TransducerNode(
                name="DemoField",
                options={"fieldhelper": "demo"},
                inputs=[
                    InputNode("name", "@id", None),
                    InputNode("annotation", "@type", None),
                    InputNode("tx_key", "@str", '"G"'),
                ],
            )
        ]
    )
    out = generate_api(ast)
    assert "AUTO-GENERATED BY YIDL COMPILER" in out
    assert "class LCDemoField(LCKind):" in out
    assert "def demo(" in out
    assert "tx_key: str = \"G\"" in out


def test_main_writes_output(tmp_path, capsys, monkeypatch):
    spec = tmp_path / "spec.yidl"
    spec.write_text(
        "transducer T: fieldhelper=t\n    inputs:\n        n: @id\n",
        encoding="utf-8",
    )
    out = tmp_path / "out.py"
    monkeypatch.setattr(sys, "argv", ["yidl", str(spec), "-o", str(out)])
    main()
    captured = capsys.readouterr()
    assert "Successfully compiled" in captured.out
    text = out.read_text(encoding="utf-8")
    assert "YIDL COMPILER" in text
    assert "class LCT(LCKind):" in text


def test_main_missing_file_exits(monkeypatch):
    monkeypatch.setattr(sys, "argv", ["yidl", "/nonexistent/path/spec.yidl"])
    with pytest.raises(SystemExit) as exc:
        main()
    assert exc.value.code == 1


@pytest.mark.skipif(not _EXAMPLE_SPEC.is_file(), reason="example spec not present")
def test_main_compiles_example_yidl(tmp_path, capsys, monkeypatch):
    out = tmp_path / "api.py"
    monkeypatch.setattr(
        sys, "argv", ["yidl", str(_EXAMPLE_SPEC), "-o", str(out)]
    )
    main()
    body = out.read_text(encoding="utf-8")
    assert "class LCManagedField(LCKind):" in body
    assert body.count("transducer") == 0  # generated Python, not YIDL source
