import argparse
import sys
from yidl.lexer import lex_yidl
from yidl.parser import YIDLParser
def map_type_hint(expr: str) -> str:
    """Translates YIDL @type expressions into Python type hints."""
    is_optional = expr.startswith("?")
    if is_optional:
        expr = expr[1:]

    res = "Any"
    if expr.startswith("@object("): res = expr[8:-1]
    elif expr.startswith("@lambda"): res = "Callable"
    elif expr.startswith("@str"): res = "str"
    elif expr == "@bool": res = "bool"
    elif expr == "@id": res = "str"
    elif expr == "@type": res = "Any"

    if is_optional:
        res = f"Optional[{res}]"
    return res

def generate_api(ast) -> str:
    """Generates public api.py-style output with LCKind classes and helpers."""
    lines = [
        "# =============================================================================",
        "# AUTO-GENERATED BY YIDL COMPILER",
        "# Do not edit manually. Update the .yidl spec and recompile.",
        "# =============================================================================",
        "from dataclasses import dataclass",
        "from typing import Any, Callable, Optional, Literal",
        "",
        "class _MissingType:",
        "    pass",
        "MISSING = _MissingType()",
        "",
        "@dataclass",
        "class LCKind:",
        "    name: str = MISSING",
        "    annotation: Any = MISSING",
        ""
    ]

    for transducer in ast.transducers:
        class_name = f"LC{transducer.name}"
        lines.append("@dataclass")
        lines.append(f"class {class_name}(LCKind):")

        helper_params = []
        helper_args = []
        has_custom_fields = False

        for inp in transducer.inputs:
            if inp.name in ("name", "annotation"):
                continue

            has_custom_fields = True
            py_type = map_type_hint(inp.type_expr)

            py_default = ""
            if inp.default_expr:
                default_val = "None" if inp.default_expr == "None" else inp.default_expr
                py_default = f" = {default_val}"
                helper_params.append(f"{inp.name}: {py_type}{py_default}")
            else:
                helper_params.append(f"{inp.name}: {py_type}")

            lines.append(f"    {inp.name}: {py_type}{py_default}")
            helper_args.append(f"{inp.name}={inp.name}")

        if not has_custom_fields:
            lines.append("    pass")

        lines.append("")

        helper_name = transducer.options.get("fieldhelper", transducer.options.get("classhelper"))
        if helper_name:
            sig = ", ".join(helper_params)
            lines.append(f"def {helper_name}({sig}) -> {class_name}:")
            lines.append(f'    """Auto-generated helper for {transducer.name}"""')
            lines.append(f"    return {class_name}(")
            for arg in helper_args:
                lines.append(f"        {arg},")
            lines.append("    )")
            lines.append("")

    return "\n".join(lines)

def main() -> None:
    parser = argparse.ArgumentParser(description="YIDL meta-compiler (lifecycle transducer specs)")
    parser.add_argument("spec_file", help="Path to the .yidl specification file")
    parser.add_argument("--out", "-o", help="Output file for generated API definitions")

    args = parser.parse_args()

    try:
        with open(args.spec_file, "r") as f:
            source = f.read()
    except FileNotFoundError:
        print(f"Error: Could not find file {args.spec_file}", file=sys.stderr)
        sys.exit(1)

    tokens = list(lex_yidl(source))
    parser_instance = YIDLParser(tokens)
    ast = parser_instance.parse()

    api_code = generate_api(ast)

    if args.out:
        with open(args.out, "w") as f:
            f.write(api_code)
        print(f"✅ Successfully compiled {len(ast.transducers)} transducers.")
        print(f"✅ Generated API written to: {args.out}")
    else:
        print(api_code)

if __name__ == "__main__":
    main()
