from __future__ import annotations

from pathlib import Path

from yidl.runtime.lifecycle import _generate_lifecycle_source
from yidl.runtime.lifecycle import field
from yidl.runtime.lifecycle import harvest_lifecycle_definition
from yidl.runtime.lifecycle import managed

OUTPUT = Path(__file__).with_name("lifecycle_constructor_perf_generated.py")
SIZES = (5, 10, 15)


def increment_factory_for(param_name: str) -> object:
    namespace: dict[str, object] = {}
    exec(
        f"def factory({param_name}):\n"
        f"    return {param_name} + 1\n",
        namespace,
    )
    return namespace["factory"]


def make_lifecycle_perf_class(field_group_size: int) -> type[object]:
    annotations: dict[str, object] = {}
    namespace: dict[str, object] = {
        "__annotations__": annotations,
        "__module__": __name__,
    }
    for index in range(field_group_size):
        name = f"plain_{index}"
        annotations[name] = "int"
        namespace[name] = field(default=index)
    for index in range(field_group_size):
        name = f"count_{index}"
        annotations[name] = "int"
        namespace[name] = managed(default=index)
    for index in range(field_group_size):
        name = f"derived_{index}"
        annotations[name] = "int"
        namespace[name] = managed(
            default_factory=increment_factory_for(f"count_{index}"),
        )
    return type(f"PerfLifecycle{field_group_size}", (), namespace)


def build_kwargs_source(size: int) -> str:
    class_name = f"PerfLifecycle{size}"
    lines = [
        f"class _{class_name}User:",
        "    pass",
        "",
        f"def _make_{class_name}_kwargs():",
        "    return {",
        f"        '_{class_name}_lifecycle_definition': {{}},",
        f"        '_{class_name}_annotations': {{",
    ]
    for index in range(size):
        lines.append(f"            'plain_{index}': 'int',")
    for index in range(size):
        lines.append(f"            'count_{index}': 'int',")
    for index in range(size):
        lines.append(f"            'derived_{index}': 'int',")
    lines.extend(
        [
            "        },",
            f"        '_{class_name}_tx_keys': (DEFAULT_TRANSACTION,),",
        ]
    )
    for index in range(size):
        lines.append(f"        '_{class_name}_plain_{index}_default': {index},")
    for index in range(size):
        lines.append(f"        '_{class_name}_count_{index}_default': {index},")
    for index in range(size):
        lines.append(
            f"        '_{class_name}_derived_{index}_default_factory': "
            f"_increment_factory_for('count_{index}'),"
        )
    lines.extend(
        [
            "    }",
            "",
            f"{class_name} = build_lifecycle_class(",
            f"    _{class_name}User,",
            f"    **_make_{class_name}_kwargs(),",
            ")",
            f"LIFECYCLE_PERF_CLASSES[{size}] = {class_name}",
            "",
        ]
    )
    return "\n".join(lines)


def strip_repeated_future_imports(source: str) -> str:
    return "\n".join(
        line
        for line in source.splitlines()
        if line != "from __future__ import annotations"
    )


def main() -> int:
    parts = [
        "from __future__ import annotations",
        "",
        "from yidl.runtime.transaction_yidl import DEFAULT_TRANSACTION",
        "",
        "# Generated by tests/data/perf/generate_lifecycle_constructor_perf_fixture.py.",
        "# This fixture keeps constructor throughput tests focused on object creation,",
        "# not on one-time YIDL assembly/source generation cost.",
        "",
        "def _increment_factory_for(param_name: str):",
        "    namespace: dict[str, object] = {}",
        "    exec(",
        '        f"def factory({param_name}):\\n"',
        '        f"    return {param_name} + 1\\n",',
        "        namespace,",
        "    )",
        '    return namespace["factory"]',
        "",
        "LIFECYCLE_PERF_CLASSES: dict[int, type[object]] = {}",
        "",
    ]
    for size in SIZES:
        print(f"generating {size}", flush=True)
        harvested = harvest_lifecycle_definition(make_lifecycle_perf_class(size))
        source = strip_repeated_future_imports(
            _generate_lifecycle_source(harvested).rstrip()
        )
        parts.extend(
            [
                f"# ---- {size} fields per group ({size * 3} total fields) ----",
                source,
                "",
                build_kwargs_source(size),
            ]
        )
    OUTPUT.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"wrote {OUTPUT} ({OUTPUT.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
