"""YIDL capsule package."""

from .base_capsule import BaseCapsule, build_base_capsule
from .build_mapper import (
    CapsuleClassBuildPlan,
    ChildPortPlan,
    RuntimePortRef,
    TemplateEdgePlan,
    build_class_source,
)
from .class_concepts import define_class_field_schema
from .core import (
    CapsuleBuilder,
    CapsuleFacade,
    CapsuleMethod,
    CapsuleMethodSurface,
    CapsuleProperty,
    CapsuleSpec,
    CapsuleSpecInstance,
    CapsuleSpecValue,
    UNSPECIFIED,
    UnspecifiedType,
    YidlCapsule,
    build,
    build_from,
)
from .definition import (
    CapsuleConcept,
    CapsuleContributor,
    CapsuleDefinition,
    CapsuleRuntime,
    capsule,
    concept,
)
from .init_concepts import (
    ASSIGNMENT,
    DEFAULTED_PARAM,
    INIT_METHOD,
    INIT_TEMPLATE_GLOBALS,
    INIT_TEMPLATE_VALUE_NAMES,
    REQUIRED_PARAM,
    build_init_capsule_definition,
    define_init_productions,
    init_class_build_plan,
)
from .init_only_capsule import (
    InitOnlyCapsule,
    InitOnlyClassDefinition,
    InitOnlyFieldSpec,
    build_init_only_capsule,
    class_definition_from_class,
    compile_capsule,
    compile_init_only_capsule,
    emit_init_only_factory_source,
    field_spec,
    render_init_only_class,
)

__all__ = [
    "BaseCapsule",
    "ASSIGNMENT",
    "CapsuleBuilder",
    "CapsuleClassBuildPlan",
    "CapsuleConcept",
    "CapsuleContributor",
    "CapsuleDefinition",
    "CapsuleFacade",
    "CapsuleMethod",
    "CapsuleMethodSurface",
    "CapsuleProperty",
    "CapsuleRuntime",
    "CapsuleSpec",
    "CapsuleSpecInstance",
    "CapsuleSpecValue",
    "ChildPortPlan",
    "DEFAULTED_PARAM",
    "INIT_METHOD",
    "INIT_TEMPLATE_GLOBALS",
    "INIT_TEMPLATE_VALUE_NAMES",
    "InitOnlyCapsule",
    "InitOnlyClassDefinition",
    "InitOnlyFieldSpec",
    "REQUIRED_PARAM",
    "RuntimePortRef",
    "TemplateEdgePlan",
    "UNSPECIFIED",
    "UnspecifiedType",
    "YidlCapsule",
    "build",
    "build_from",
    "build_base_capsule",
    "build_class_source",
    "build_init_capsule_definition",
    "build_init_only_capsule",
    "capsule",
    "class_definition_from_class",
    "compile_capsule",
    "compile_init_only_capsule",
    "concept",
    "define_class_field_schema",
    "define_init_productions",
    "emit_init_only_factory_source",
    "field_spec",
    "init_class_build_plan",
    "render_init_only_class",
]
