"""YIDL capsule package."""

from .base_capsule import BaseCapsule, build_base_capsule
from .core import (
    CapsuleBuilder,
    CapsuleFacade,
    CapsuleMethod,
    CapsuleMethodSurface,
    CapsuleProperty,
    CapsuleSpec,
    CapsuleSpecInstance,
    CapsuleSpecValue,
    UNSPECIFIED,
    UnspecifiedType,
    YidlCapsule,
    build,
    build_from,
)
from .init_only_capsule import (
    InitOnlyCapsule,
    InitOnlyClassDefinition,
    InitOnlyFieldSpec,
    build_init_only_capsule,
    class_definition_from_class,
    compile_capsule,
    compile_init_only_capsule,
    emit_init_only_factory_source,
    field_spec,
    render_init_only_class,
)

__all__ = [
    "BaseCapsule",
    "CapsuleBuilder",
    "CapsuleFacade",
    "CapsuleMethod",
    "CapsuleMethodSurface",
    "CapsuleProperty",
    "CapsuleSpec",
    "CapsuleSpecInstance",
    "CapsuleSpecValue",
    "InitOnlyCapsule",
    "InitOnlyClassDefinition",
    "InitOnlyFieldSpec",
    "UNSPECIFIED",
    "UnspecifiedType",
    "YidlCapsule",
    "build",
    "build_from",
    "build_base_capsule",
    "build_init_only_capsule",
    "class_definition_from_class",
    "compile_capsule",
    "compile_init_only_capsule",
    "emit_init_only_factory_source",
    "field_spec",
    "render_init_only_class",
]
